### ISSUE TITLE
Error while creating container 

### ISSUE THREAD

**Issue by paveldournov** [tensorflow/cloud#47]
### Environment: 
     Mac, 
     Python 3.7, 
     gcloud 
         Google Cloud SDK 300.0.0
         bq 2.0.58
         core 2020.07.06
         gsutil 4.51
         kubectl 2020.05.01

### Steps:
  - create the sample mnist.py, run it locally - OK
  - create a script to submit it to GCP
    ```
     import tensorflow_cloud as tfc
     tfc.run(entry_point='mnist_train.py')
     ```
  - run the script 

### Expected:
The script build a container and runs the job in GCP

### Observed:
An exception while building container:

```
(tfcloud) :tf_cloud$ python run_on_gcp.py 
INFO:tensorflow_cloud.containerize:Building docker image: gcr.io/my-project/tf_cloud_train:c74be2d8_b6cc_4832_9522_b1c69ded7f95
INFO:tensorflow_cloud.containerize:{"stream":"Step 1/4 : FROM tensorflow/tensorflow:2.2.0-gpu"} {"stream":"\n"}
   Traceback (most recent call last):
      File "/Users/dournov/tf_cloud/tfcloud/lib/python3.7/site-packages/tensorflow_cloud/containerize.py", line 287, in _get_logs
    line = json.loads(unicode_line)
  File "/Users/dournov/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/dournov/miniconda3/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 62)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_on_gcp.py", line 2, in <module>
    tfc.run(entry_point='mnist_train.py')
  File "/Users/dournov/tf_cloud/tfcloud/lib/python3.7/site-packages/tensorflow_cloud/run.py", line 188, in run
    docker_img_uri = container_builder.get_docker_image()
  File "/Users/dournov/tf_cloud/tfcloud/lib/python3.7/site-packages/tensorflow_cloud/containerize.py", line 235, in get_docker_image
    image_uri = self._build_docker_image()
  File "/Users/dournov/tf_cloud/tfcloud/lib/python3.7/site-packages/tensorflow_cloud/containerize.py", line 255, in _build_docker_image
    self._get_logs(bld_logs_generator, 'build')
  File "/Users/dournov/tf_cloud/tfcloud/lib/python3.7/site-packages/tensorflow_cloud/containerize.py", line 294, in _get_logs
    'There was an error decoding the Docker logs')
RuntimeError: There was an error decoding the Docker logs
```

**Comment by pavithrasv** [comment]
Thank you for the issue @paveldournov. Are you consistently seeing this same issue? Could you provide more information on this or try the latest release? I am unable to reproduce this on my environment. Any additional information would help us debug and fix this.

**Comment by paveldournov** [comment]
It no longer reproduces on the most recent release. Closing.

**Comment by pavithrasv** [comment]
Thank you for confirming!
